export default [
  {
    id: 1,
    name: 'Treebo Select Wilson Garden',
    locality: 'Wilson Garden, Bangalore',
    price: '₹2599',
    thumbnail: 'https://cs-images.treebo.com/Treebo_Select_Wilson_Garden/Mahogany/Mahogany_(78).jpg?w=138&h=138&fit=crop&fm=pjpg',
    tag: 'Cheapest Price',
  },
  {
    id: 2,
    name: 'Treebo Crystal Castle',
    locality: 'JP Nagar, Bangalore',
    price: '₹2699',
    thumbnail: 'https://cs-images.treebo.com/Treebo_Crystal_Castle/Crystal_Castle_Oak_Queen_Bed_2.jpg?w=138&h=135&fit=crop&fm=pjpg',
    tag: '4 rooms left',
  },
  {
    id: 3,
    name: 'Treebo Cynosure Suites',
    locality: 'Infantry Road, Bangalore',
    price: '₹2399',
    thumbnail: 'https://cs-images.treebo.com/Treebo_Cynosure_Suites/Mahogany_(7).jpg?w=138&h=135&fit=crop&fm=pjpg',
    tag: '1 room left',
  },
  {
    id: 4,
    name: 'Treebo El Cielo',
    locality: 'Bangalore',
    price: '₹2799',
    thumbnail: 'https://cs-images.treebo.com/Treeb_El_Cielo/Maple/Maple_(88).jpg?w=138&h=135&fit=crop&fm=pjpg',
    tag: 'Filling Fast',
  },
  {
    id: 5,
    name: 'Treebo Edha Suites',
    locality: 'Koramangala, Bangalore',
    price: '₹2999',
    thumbnail: 'https://cs-images.treebo.com/Treebo_Edha_Suites/Mahogany/Mahogany(5).jpg?w=138&h=135&fit=crop&fm=pjpg',
    tag: 'Cheapest Price',
  },
  {
    id: 6,
    name: 'Treebo Raj Premier',
    locality: 'Indiranagar, Bangalore',
    price: '₹3199',
    thumbnail: 'https://cs-images.treebo.com/Treebo_Raj_Premier/raj_premere_Oak__King_B3.jpg?w=138&h=135&fit=crop&fm=pjpg',
    tag: '2 rooms left',
  },
];
